# Build pipeline to deploy to firebase
pool:
  vmImage: ubuntu-16.04
  demands:
    - npm
    - node.js

trigger:
  branches:
    include:
      - master
      - dev

steps:
  - task: NodeTool@0
    displayName: "Use Node 12.x"
    inputs:
      versionSpec: 12.x

  - task: CmdLine@2
    inputs:
      script: 'npm i -g gridsome firebase-tools'

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: CmdLine@2
    inputs:
      script: 'npm run build'

  - task: CmdLine@2
    inputs:
      script: 'firebase deploy --token "$FIREBASE_TOKEN"'
