# A Pure Build pipeline to test if everything works or not
pool:
  vmImage: ubuntu-16.04
  demands:
    - npm
    - node.js

trigger:
  branches:
    include:
      - master
      - dev

steps:
  - task: NodeTool@0
    displayName: "Use Node 12.x"
    inputs:
      versionSpec: 12.x

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false
